validate:
  VALID_EMAIL_REGEX: !ruby/regexp '/\A[^@\s]+@[^@\s]+\z/'
account:
  admin:
    address: "Thôn Nội - Đức Thượng - Hoài Đức - Hà Nội"
    email: "nguyenvanbay.ptit@gmail.com"
    name: "Nguyễn Văn Bảy"
    password: "111111"
    phone: "0962199791"
    role: "admin"
  manager:
    address: "Thôn Nội - Đức Thượng - Hoài Đức - Hà Nội"
    email: "nguyenvantam.no1@gmail.com"
    name: "Nguyễn Văn Tám"
    password: "111111"
    phone: "0962199791"
    role: "manager"
  user:
    password: "111111"
    role: "normal"
omniauth:
  facebook: "facebook"
user: 
  min_address_length: 3
  max_address_length: 128
  VALID_EMAIL_REGEX: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  max_phone_length: 250
  min_name_length: 1
  max_name_length: 150
  role:
    admin: "danger"
    manager: "warning"
    normal: "info"
    enum_admin: "admin"
    enum_manager: "manager"
    enum_normal: "mormal"
    number_admin: 1
    number_manager: 2
    number_normal: 0
admin:
  user:
    num_in_page: 10
page:
  num_in_page: 10
  start: 1
theme:
  theme_config: "twitter-bootstrap-4"
